### PR TITLE
Fix config path with Atom 1.25

### LINKED ISSUE #401: Uncaught Error: ENOENT: no such file or directory, open 'undefined/init.coffee'
[Enter steps to reproduce:]

1. Open Atom Beta
1. Wait for the `Your settings are out of date` notification
1. Click `Restore`
1. Observe error

**Atom**: 1.25.0-beta0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.3

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'undefined/init.coffee'

```
At fs.js:584

Error: ENOENT: no such file or directory, open 'undefined/init.coffee'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at /packages/sync-settings/lib/sync-settings.coffee:247:16
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
     -0:13.9.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-gruvbox-plus-syntax.theme-one-dark-ui.teletype-Authenticated)
```

### Non-Core Packages

```
atom-chai-snippets 0.3.0 
atom-ide-ui 0.8.1 
atom-material-ui 2.1.1 
atom-ternjs 0.18.3 
autocomplete-json 5.5.2 
autocomplete-modules 1.10.0 
blame 1.0.1 
build 0.70.0 
build-make 0.13.0 
docblockr 0.13.6 
editorconfig 2.2.2 
file-icons 2.1.16 
firestore-rules-grammar 0.3.0 
git-plus 7.10.0 
git-projects 1.17.0 
go-debug 1.6.0 
go-plus 5.8.2 
gruvbox-plus-syntax 1.3.1 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-css 0.2.0 
ide-docker 0.0.2 
ide-go 0.6.1 
ide-json 0.2.0 
ide-typescript 0.7.2 
ide-yaml 0.4.2 
indent-guide-improved 1.4.13 
js-hyperclick 1.13.0 
language-babel 2.83.4 
language-diff 0.7.0 
language-docker 1.1.8 
language-dotenv 1.1.1 
language-gitignore 0.3.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-terraform 0.8.1 
linter-eslint 8.4.1 
linter-markdown 5.2.0 
linter-package-json-validator 2.0.0 
linter-shellcheck 1.4.6 
linter-terraform-syntax 1.2.2 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-git-diff 4.3.1 
minimap-linter 2.1.3 
platformio-ide-terminal 2.8.0 
pristine-ui 1.1.11 
pure-syntax 0.3.0 
sort-lines 0.18.0 
standardjs-snippets 2.6.2 
sync-settings 0.8.3 
teletype 0.7.0 
todo-show 2.1.0 
tree-view-autoresize 2.3.0 
```

### PR DESCRIPTION
**Pull request by ykpythemind**
when Atom beta 1.25.0beta0,  `atom.config.configDirPath` seems undefined. 

resolve #401

### CODE REVIEW

**Comment by UziTech** [comment]
should probably use [`atom.getConfigDirPath()`](https://github.com/atom/atom/blob/1f6c57ce619a50301f76f4cea52da48ce8c739c1/src/atom-environment.js#L1276-L1279) instead of the `atom.configDirPath` directly to prevent this same issue in the future.

**Comment by ykpythemind** [comment]
@UziTech Thank you. fixed.

**Comment by ykpythemind** [comment]
This PR will also resolve #402 #404

File: spec/sync-settings-spec.coffee [hunk 1]
```diff
@@ -145,15 +145,16 @@ describe "SyncSettings", ->
...
         atom.config.set('sync-settings.syncInit', true)
+        initPath = atom.getUserInitScriptPath()
         run (cb) ->
           SyncSettings.backup cb
         , ->
           run (cb) =>
             SyncSettings.createClient().gists.get({id: @gistId}, cb)
           , (err, res) ->
-            expect(res.files['init.coffee']).toBeDefined()
+            expect(res.files[path.basename(initPath)]).toBeDefined()
```
Comment (dirk-thomas) [inline spec/sync-settings-spec.coffee]: Please keep the changes for the `init` file in a separate PR since they are unrelated to the config path problem addressed in this PR.

Comment (ykpythemind) [reply spec/sync-settings-spec.coffee]: OK, fixed. 

But in my environment, both init.coffee and init.js exists. 

```
      it "back up the user init.coffee file", ->
        atom.config.set('sync-settings.syncInit', true)
        run (cb) ->
          SyncSettings.backup cb
```

this test backups init.js instead of init.coffee, so my test fails locally.

Comment (dirk-thomas) [reply spec/sync-settings-spec.coffee]: The patch for the init files is still valid. Please create a separate PR for it though. Then they can get merged in whatever order is necessary to keep CI passing.

Comment (ykpythemind) [reply spec/sync-settings-spec.coffee]: OK, i will create.

**Comment by ykpythemind** [comment]
opened #405

**Comment by dirk-thomas** [comment]
As shown in #406 this (together with #405) makes the specs pass with Atom 1.25.0-beta1.

Thank you for the patch!
